
-- STEP 1:	CREATE NEW LOGIN : FOR SERVER CONNECTION
CREATE LOGIN Jeny_LOGIN WITH PASSWORD  = 'admin@123$'


-- STEP 2:	CREATE A USER FOR ABOVE LOGIN : FOR DATABASE CONNECTION IN MASTER
CREATE USER UserForLogin FOR LOGIN Jeny_LOGIN


-- CONNECT TO REQUIRED DATABASE OR POOL
-- STEP 3:	CREATE A USER FOR ABOVE LOGIN : FOR DATABASE CONNECTION IN AZURE SQL DB / POOL
CREATE USER UserForLogin FOR LOGIN Jeny_LOGIN


-- STEP 4: ASSIGN PERMISSIONS ON OBJECTS (TABLES, VIEWS...) TO USER:
	GRANT SELECT ON SALES_DATA TO UserForLogin 
	GRANT INSERT ON CUSTOMERS_DATA TO UserForLogin 
	GRANT EXECUTE ON SP_MERGE TO UserForLogin


-- STEP 5: DATABASE LEVEL / SQL POOL LEVEL PERMISSIONS:
	ALTER ROLE DB_DATAREADER ADD MEMBER UserForLogin
	ALTER ROLE DB_DATAWRITER ADD MEMBER UserForLogin
	ALTER ROLE DB_DDLADMIN ADD MEMBER UserForLogin

